### ISSUE TITLE
could not select device driver “” with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by eddydw** [docker/for-win#7581]
I am using WSL2 and docker and GPU aware docker.

I have windows 10 version 2004 (build 20161.1000) I have installed WSL 2 and have Docker Desktop 2.3.0.3 on my Windows System running. I have Ubuntu 18.04 LTS installed in WSL 2 too. I have installed the NVIDIA driver enter image description here 
![image](https://user-images.githubusercontent.com/4919435/86808231-f52afe00-c07a-11ea-833d-afbe1eea7875.png)

The linux version is 4.19.121-microsoft-standard. The NVIDIA driver version is 455.41 for my Laptop GPU QUADRO M2000M. Actually I followed all the steps described in https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2 until the step where I have to run "sudo service docker stop" in an Ubuntu terminal.

This results in a message docker: unrecognized service.

I have to restart docker desktop in Windows 10 in order to get the daemon running.

I test then in the Ubuntu terminal: docker run hello-world ==> this runs fine Also the command docker run -it ubuntu bash ==> runs the file in the Ubuntu terminal os WSL 2.

BUT when I run : docker run -u (id−u):(id -g) -it --gpus all -p 8888:8888 tensorflow/tensorflow:latest-gpu-py3-jupyter

then I get the error : docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

This involves Microsoft, Ubuntu, NVIDIA. I have searched the support sites but could not find anything that solves my problem.

Can anyone help me here?

**Comment by wicca1984** [comment]
I was running into the same problem.
I followed this article https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-docker

I think there's a problem with the Docker installation part
"Install Docker
Use the Docker installation script to install Docker for your choice of WSL 2 Linux distribution. Note that NVIDIA Container Toolkit does not yet support Docker Desktop WSL 2 backend."

**Comment by stephen-turner** [comment]
Thanks for the reports. As you know, Microsoft have only just released GPU support in WSL 2 to the Insiders builds, so this is all very new. We are aware that the Nvidia drivers don't yet run on Docker Desktop, and we're working on it.

**Comment by stephen-turner** [comment]
Also, we have an item about this on our public roadmap -- docker/roadmap#96 -- feel free to give it a thumbs up if you haven't already.

**Comment by eddydw** [comment]
Hi Stephen

Thanks for the update.

Best regards
Eddy

Op wo 8 jul. 2020 om 17:36 schreef Stephen Turner <notifications@github.com

**Comment by eddydw** [comment]
Hi

I did follow the instruction without any change tough

Kind regards
Eddy

---------- Forwarded message ---------
Van: wicca <notifications@github.com>
Date: wo 8 jul. 2020 om 11:18
Subject: Re: [docker/for-win] could not select device driver “” with
capabilities: [[gpu]] (#7581)
To: docker/for-win <for-win@noreply.github.com>
Cc: eddydw <eddy.de.waegeneer@gmail.com>, Author <author@noreply.github.com>


I was running into the same problem.
I followed this article
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-docker

I think there's a problem with the Docker installation part
"Install Docker
Use the Docker installation script to install Docker for your choice of WSL
2 Linux distribution. Note that NVIDIA Container Toolkit does not yet
support Docker Desktop WSL 2 backend."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/for-win/issues/7581#issuecomment-655399013>, or
unsubscribe

**Comment by jnoelvictorino** [comment]
I also recently encountered this roadblock. What I did was to keep Docker Desktop installed in Windows 10.
But I also installed Docker inside WSL2 distro (as mentioned in the instructions). 

This setup is working for now, but it is not ideal.
When I want to use Docker to run with GPUs, I have to turn off Docker Desktop and turn on Docker inside WSL2 distro.
Some goes if I want to use Docker Desktop only.

**Comment by dshep** [comment]
I finally got it to work.

Installed a new instance of ubuntu 18.04 that was not my default WSL2 instance, and not linked to docker for windows.

Installed docker into this instance following the instructions here:  https://dev.to/bartr/install-docker-on-windows-subsystem-for-linux-v2-ubuntu-5dl7

I still got an error with mounts when i ran the hello world container.  This was fixed with the following 2 commands (from this issue:  https://github.com/microsoft/WSL/issues/4189)
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd

Once i had docker running successfully, I followed the instruction this instructions to get it docker instances running using my RTX GPU: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#setting-containers.  I skipped the Running Cuda applications section because the demo's have changed.  There are also build issues with the RTX cards, because not all the demos support the version of CUDA that card does, so you have to manually set compile flags to reduce the version.

Hope this helps

**Comment by Agrover112** [comment]
Yes you are right even I skipped them

**Comment by jnoelvictorino** [comment]
Thanks for the tip @dshep! 
Docker Desktop and Docker inside WSL2 distro now work at the same time.

I made `docker-desktop` the default distro for WSL2
```
wsl -S docker-desktop
```

Then in the Docker Desktop settings, I did **not** `Enable integration with additional distros: Ubuntu`

**Comment by tadam98** [comment]
This makes it work.
Basically install docker on wsl2.
https://dev.to/bartr/install-docker-on-windows-subsystem-for-linux-v2-ubuntu-5dl7 

After restart of wsl2 do the following procedure:
```
$ docker ps
$ docker ps -aq
$ docker stop $(docker ps -aq)
$ docker stop # dockers reported by ps
$ rm ~/.docker/config.json
$ sudo service docker stop
$ sudo service docker start
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
$ docker ps
$ docker run hello-world
$ docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
GPU Device 0: "GeForce RTX 2080 Ti" with compute capability 7.5

> Compute 7.5 CUDA device: [GeForce RTX 2080 Ti]
69632 bodies, total time for 10 iterations: 117.583 ms
= 412.357 billion interactions per second
= 8247.147 single-precision GFLOP/s at 20 flops per interaction
```

**Comment by jnoelvictorino** [comment]
Yes, exactly! 💯 
Whenever I restart my machine, I had to repeat these steps:
```
$ sudo service docker start
$ sudo mkdir /sys/fs/cgroup/systemd # sometimes needed, sometimes not needed
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd # sometimes needed, sometimes not needed
```

So, I added these commands in my `~/.bash_profile` or `~/.bashrc` or `~/.profile`

**Comment by tadam98** [comment]
Windows insider updated to 20262.1
With the update, the regular nvidia driver was re-installed. Not good for wsl2.
Also, nvidia issued a *new* driver that you should install in windows:
https://developer.nvidia.com/cuda/wsl
The new drive is 465.12
Download and install it.
***You must reboot after the install or wsl2 will not see the gpu as of yet*.**
Start wsl2
```
$ python
> import tensorflow as tf
>  tf.test.is_gpu_available()
2020-11-19 17:15:13.395676: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
True
```
Then do the above docker procedures to check that the docker aslo works.
In my case, it works fine.

**Comment by stephen-turner** [comment]
We released a preview of GPU support in Docker Desktop on WSL 2 to the users on our development preview program yesterday. If you're interested in joining the program, please see https://www.docker.com/blog/expanding-dockers-developer-preview-program/.

**Comment by tadam98** [comment]
I am interested.
As I noted, there are two issues. One is docker gpu support which I solved by simply installing docker in wsl2. Second is that docker-compose does not support gpu dockers (regardless of wsl2) which is solved by using the dev version I mentioned.

Both issues need to be addressed.

Best,
Mickey
________________________________

**Comment by Agrover112** [comment]
> Yes, exactly! 💯
> Whenever I restart my machine, I had to repeat these steps:
> 
> ```
> $ sudo service docker start
> $ sudo mkdir /sys/fs/cgroup/systemd # sometimes needed, sometimes not needed
> $ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd # sometimes needed, sometimes not needed
> ```
> 
> So, I added these commands in my `~/.bash_profile` or `~/.bashrc` or `~/.profile`

Does this solve the problem? @tadam98

**Comment by mattkenefick** [comment]
Are we still in workaround territory or do we have a proper solution RE: @stephen-turner 's preview

**Comment by stephen-turner** [comment]
This was released in Docker Desktop back in January. Note that it still requires an Insiders build of Windows until Microsoft include the necessary functionality in a GA build. For that reason it's still officially experimental, but it's complete from the Docker side.
